title: "Rotman PhD Association"
description: "Internal portal for Rotman PhD students"
baseurl: ""
url: "https://rotmanphd.ca"

markdown: kramdown
permalink: pretty

collections:
  notices:
    output: false
    sort_by: date
  events:
    output: false
    sort_by: date
  resources:
    output: true
    permalink: /resources/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"
